---
title: "Metapopulasjoner"
description: > 
  For vi er legion.
draft: false
author:
  - name: Endre Grüner Ofstad
categories:
  - Økologi
  - Økosystem
output:
  distill::distill_article:
    self_contained: false
    code_folding: true
---

Test

```{r, cache = T}
library(data.table)
library(ggplot2);library(cowplot);library(scales);library(gridExtra)

nSimulations = 10
ParameterSpace = expand.grid(nIterations = 1:nSimulations,
                             #RangeØyer = seq(40,60,length.out = 1),
                             RangeStartProp = seq(.35,.6,length.out = 1),
                             RangeLandskap = seq(3.4,3.7,length.out = 1),
                             RangeKonstantC = seq(.24,.75,length.out =  1),# .23->.24
                             RangeKonstantE = seq(60,100,length.out = 1),# 325->320
                             eNoise = seq(0,3,length.out = 1))
setorder(ParameterSpace, nIterations)

ParameterSpace$SnittPrevalens = NA
ParameterSpace$SdPrevalens = NA
ParameterSpace$MinPrevalens = NA
ParameterSpace$AndelUtvikling = NA
iteration = 0
# lengde på tidsserie
tmax = 100
RangeØyer = 40
nØyer = RangeØyer # ParameterSpace$RangeØyer[i] #i

TidsArray = array(rep(0, tmax*nØyer), 
                  dim = c(tmax, nØyer,  nrow(ParameterSpace)))

TidsserieKoloniseringsrater = array(rep(0, tmax*nØyer), 
                                    dim = c(tmax, nØyer, nrow(ParameterSpace)))

GeografiArray = array(rep(NA, 3*nØyer),
                      dim = c(3, nØyer, nrow(ParameterSpace)))


for(i in 1:nrow(ParameterSpace)){
  #print(paste(i , "av", nrow(ParameterSpace)))
  # Antall øyer/habitat i systemet
  
  
  
  iteration <- ParameterSpace$nIterations[i]
  
  AntallBebodd = ParameterSpace$RangeStartProp[i]*nØyer #i
  set.seed(iteration) # slik at ulike miljøstøy-nivå vil testes på de samme øy-konfigurasjonene
  Bebodd = sample(1:nØyer,AntallBebodd)
  
  
  Tilstede = rep(0, nØyer)
  Tilstede[Bebodd]<-1
  
  TidsserieTilstede = matrix(rep(rep(NA, nØyer), tmax), ncol = nØyer)
  TidsserieTilstede[1,]<-Tilstede
  
  TidsArray[1,,iteration]<-Tilstede
  TidsserieKoloniseringsrater[1,,iteration]<-Tilstede
  
  # tilfeldig plassering av øyene
  ArenaStørrelse = ParameterSpace$RangeLandskap[i]
  set.seed(iteration) # slik at ulike miljøstøy-nivå vil testes på de samme øy-konfigurasjonene
  xPos = runif(n = nØyer, min = 0, max = ArenaStørrelse)
  set.seed(-iteration) # slik at ulike miljøstøy-nivå vil testes på de samme øy-konfigurasjonene
  yPos = runif(n = nØyer, min = 0, max = ArenaStørrelse)
  
  # Tilfeldig størrelse
  set.seed(iteration) # slik at ulike miljøstøy-nivå vil testes på de samme øy-konfigurasjonene
  ØyStr = rlnorm(n = nØyer, meanlog = .1, sdlog = .2) #Ai
  
  GeografiArray[,,i]<-rbind(ØyStr, xPos, yPos)
  # Regn ut mellom-øy avstand
  MellomØyAvstand = dist(cbind(xPos, yPos), diag = T, upper = T) # dij
  Alpha = -1#1/mean(MellomØyAvstand)
  # Konstanter
  c_konstant = ParameterSpace$RangeKonstantC[i]
  e_konstant = ParameterSpace$RangeKonstantE[i]
  
  eNoise = ParameterSpace$eNoise[i]
  # Utryddelsesrater er konstant over tid
  UtryddelsesRateØy_i = e_konstant/ØyStr
  
  # fra Hanski, Ilkka, et al. "The quantitative incidence function model and persistence of an endangered butterfly metapopulation." Conservation Biology 10.2 (1996): 578-590.
  # ØystrEffekt = 0.952
  # muTick = 0.158
  
  # AjAi = sapply(ØyStr, function(x) x*ØyStr)
  # mij = exp(-Alpha*as.matrix(MellomØyAvstand))*AjAi # number of immigrants
  
  # Tidssteg 
  t = 2
  NoiseE = rnorm(n = tmax, sd = eNoise)
  while(t<tmax){
    
    KoloniseringsRateØy_i = sapply(1:nØyer, function(i){
      Aj = ØyStr[-i]
      Aj = Aj +NoiseE
      c_konstant*sum(Tilstede[-i]*Aj*
                       exp(-Alpha*as.matrix(MellomØyAvstand)[-i,i]))}) # Si
    
    
    TidsserieKoloniseringsrater[t,,i]<-KoloniseringsRateØy_i
    
    
    # Sannsynligheten for bebodd øy
    Pi = KoloniseringsRateØy_i/(KoloniseringsRateØy_i + UtryddelsesRateØy_i) # Også kjent som Ji
    Pi = ifelse(Pi>1,1,ifelse(Pi<0,0,Pi))
    
    Kolonisert = sapply(Pi, function(x) sample(0:1, 1, prob = c(1-x,x)))
    
    # Oppdater bebodd-status
    Tilstede<-Kolonisert
    TidsserieTilstede[t,]<-Tilstede
    TidsArray[t,,i]<-Tilstede
    
    # Oppdater tidssteg
    t = t+1
  }
  
  ParameterSpace$SnittPrevalens[i] = median(rowMeans(TidsserieTilstede), na.rm = T)
  ParameterSpace$SdPrevalens[i] = sd(rowMeans(TidsserieTilstede), na.rm = T)
  ParameterSpace$MinPrevalens[i] = min(rowMeans(TidsserieTilstede), na.rm = T)
  ParameterSpace$AndelUtvikling[i] = coef(lm(rowMeans(TidsserieTilstede)~I(1:length(rowMeans(TidsserieTilstede)))))[2]
  if(i==nrow(ParameterSpace)){
    saveRDS(list(ParameterSpace = ParameterSpace,
                 Geografi = GeografiArray,
                 TidsArray = TidsArray,
                 TidsserieKoloniseringsrater = TidsserieKoloniseringsrater),
            "ParameterSpace_MetaPopStoch.rds")
  }
}

p1 = ggplot(data = ParameterSpace, aes(y = MinPrevalens, x = eNoise, group = factor(eNoise)))+geom_boxplot()+theme_cowplot()+
  theme(axis.title.x = element_blank(), axis.text.x = element_blank())+ylab("Andel (minimum)")
p2 = ggplot(data = ParameterSpace, aes(y = SnittPrevalens, x = eNoise, group = factor(eNoise)))+geom_boxplot()+theme_cowplot()+
  theme(axis.title.x = element_blank(), axis.text.x = element_blank())+ylab("Andel (gj.snitt)")

p3 = ggplot(data = ParameterSpace, aes(y = AndelUtvikling*200, x = eNoise, group = factor(eNoise)))+geom_hline(yintercept = 0, linetype="dashed")+theme_cowplot()+
  geom_boxplot()+ylab("Andelsvekst per år x 200") + xlab("Miljøstokastisitet")#+
#scale_y_continuous(breaks = seq(-.2,.2,.1))+coord_cartesian(ylim = c(-0.1,0.1))

grid.arrange(p1,p2,p3)


Geografi = GeografiArray#aa$Geografi
TidsArray = TidsArray#aa$TidsArray
TidsserieKoloniseringsrater = TidsserieKoloniseringsrater#aa$TidsserieKoloniseringsrater

#### Centrality ####
# Eigenvector centrality er et mål på hvor mange noder som peker til deg. 
# Per parametersetting
Centrality = lapply(1:dim(Geografi)[3], function(x){
  # Per landskap
  dij = as.matrix(dist(cbind(Geografi[2,,x], Geografi[3,,x]), diag = T, upper = T))
  Centrality = sapply(1:nrow(dij), function(i){
    js = sapply(1:ncol(dij), function(j){
      exp(dij[i,j])*Geografi[1,i,x]*Geografi[1,j,x]
    })
    js
  })
  diag(Centrality)<-0 # set i = j <- 0
  Eigens = eigen(Centrality)
  EVec = Eigens$vectors[,1]^2
  EVec = EVec/sum(EVec)
  
  list(Eigenvector = EVec,
       EigenValue = Eigens$value[1])
}) 

ParameterSpace$EigenvalueCentrality<-lapply(Centrality, function(x) x$EigenValue)

## Connectivity ####
Alpha = 1/1 # Alpha beskriver overlevelse for spredningen, dvs. 1/gjennomsnittlig spredningsdistanse
# Per parametersetting
Connectivity = lapply(1:dim(Geografi)[3], function(x){
  # Per landskap
  dij = as.matrix(dist(cbind(Geografi[2,,x], Geografi[3,,x]), diag = T, upper = T))
  # Geographic aspect
  Geo = exp(-Alpha*dij)*Geografi[1,,x]*dij # ganger en siste med dij for å få ignorer i = j, dvs. avstand med seg selv
  # Per tidssteg
  Si_per_t = t(sapply(1:nrow(TidsArray), function(T){
    # per øy
    Si = sapply(1:ncol(TidsArray), function(Ø){
      Si = sum(Alpha*TidsArray[T,,x]*Geo[Ø,])
    })
    Si
  }))
}) 

Connectivities = sapply(Connectivity, function(x){
  colMeans(x)
})


### Eksempel
df = as.data.frame(t(Geografi[,,1]))
names(df)<- c("Areal", "xPos", "yPos")

#df$Connectivity = colMeans(t(Connectivities))
df$Connectivity = t(Connectivities)[1,]
df$EigenCentrality = Centrality[[1]]$Eigenvector^2*Centrality[[1]]$EigenValue

#sd(t(Connectivities)[1,])/mean(t(Connectivities)[1,])
ggplot()+
  geom_point(data = df, aes(x = xPos, y = yPos, size = Connectivity, col = Connectivity))
ggplot()+
  geom_point(data = df, 
             aes(x = xPos, y = yPos, 
                 size = 1/log(EigenCentrality), 
                 col = log(EigenCentrality)))

ParameterSpace = as.data.table(ParameterSpace)
ParameterSpace[,AverageConnectivity:=colMeans(Connectivities)]
#with(ParameterSpace, boxplot(log(EigenvalueCentrality)~eNoise))
#with(ParameterSpace, boxplot(AverageConnectivity~eNoise))

# Hettemåke foraging flight 4.6-11.8 km flight range # https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.6291
# sildemåke 30.9 #https://www.researchgate.net/publication/306119852_Terrestrial_and_Marine_Foraging_Strategies_of_an_Opportunistic_Seabird_Species_Breeding_in_the_Wadden_Sea/link/57b2ef8508aeaf239baefb27/download

# Øyer som har bedre tilknytning har bedre vekst

ggplot(data = ParameterSpace,
       mapping = aes(x = unlist(EigenvalueCentrality), 
                     y = AndelUtvikling))+
  geom_point()+
  stat_smooth(method="lm")

```

La oss nå se på et mer konkret eksempel.

```{r, cache = T,eval = T,  message=FALSE, echo=FALSE}
library(data.table)
library(sf)
library(ggmap)
library(mapproj)
library(cowplot)
library(gridExtra)
th = theme_cowplot()+
  theme(axis.text=element_blank(),axis.title=element_blank(), legend.position = "none")
library(sp)

VO = fread("Verneomraader_centroider.csv")
#VO = VO[-1,]
#Mosvatnet
#531039,61; N: 6539879 Ø: 310963
# Klostervågen
#847287,21; N: 6556056 Ø: 304732

Geografi = VOgeo = as.matrix(VO[,c("Areal", "PosX", "PosY")])
VOgeo1 = rbind(VOgeo, c(847287.21, 304732, 6556056)) # Klostervågen
VOgeo2 = rbind(VOgeo, c(531039.61, 310963, 6539879)) # Mosvatnet
VOgeo3 = rbind(VOgeo2, c(847287.21, 304732, 6556056)) # Begge to

Centrality = function(Geografi, DispersalDistance = 30.9, Alpha = NULL, unit = "m"){
  # Geografi = dataramme med areal, x og y koordinate
  Areal = Geografi[,1]
  
  if(unit=="m"){
    Areal = Areal/1000000
  }
  
  dij = as.matrix(dist(cbind(Geografi[,2], Geografi[,3]), diag = T, upper = T))
  if(unit == "m"){
    dij = dij/1000# transform from meter to kilometer
    
  }
  
  
  Alpha = 1/DispersalDistance
  
  Si = sapply(1:nrow(Geografi), function(i){
    Geo = sum(exp(-Alpha*dij[i,-i])*Geografi[-i,1]) 
  })
  
  M = sapply(seq_along(Areal), function(i){
    sapply(seq_along(Areal), function(j){
      exp(-Alpha*dij[i,j])*Areal[i]*Areal[j]
    })
  })
  
  diag(M)<-0
  ev = eigen(M)$vectors[,1]^2
  ev = ev/(sum(ev))
  we = ev*eigen(M)$value[1]
  
  
  list(Centrality = Si,
       EigenValue = eigen(M)$value[1],
       Eigenvectors = we)
}

Measures = Centrality(Geografi = VOgeo)
Plotting = function(Geografi = VOgeo3, AntallNye = 0){
  InputData = as.data.frame(Geografi)
  
  pp = st_as_sf(SpatialPoints(coords = InputData[,2:3]))
  st_crs(pp)<-32632
  bb = st_bbox(pp)
  pp2 = st_transform(pp, 4326)
  
  VOs = data.frame(st_coordinates(st_transform(pp, 4326)))
  names(VOs)<-c("PosX", "PosY")
  VOs$EV = log(Centrality(Geografi = InputData)$Eigenvectors)
  
  ## Plot kartet
  aaa = get_map(c(left = min(VOs[,1])-.2, 
                  right = max(VOs[,1])+.2,
                  bottom = min(VOs[,2])-.2, 
                  top = max(VOs[,2])+.2))
  
  Labs = data.frame(Y = max(VOs$PosY),#as.numeric(attr(aaa, "bb")[3]),
                    X = min(VOs$PosX),#as.numeric(attr(aaa, "bb")[2]), 
                    MC = paste("Metapopulasjonskapasitet = ",
                               round(Centrality(Geografi = 
                                                  InputData)$EigenValue,2)))
  
  ggmap(aaa)+
    xlab("Lengdegrad")+ ylab("Breddegrad")+theme_cowplot()+
    geom_point(data= VOs, 
               mapping = aes(x = PosX, y = PosY,
                             size = EV, col = EV))+
    geom_point(data = as.data.frame(tail(VOs,AntallNye)),
               mapping = aes(x = PosX, y = PosY), col = "red")+
    geom_label(data = Labs, 
               mapping = aes(y = Y, x = X,
                             label = MC),
               fontface = "bold", fill = alpha("white",0.5),
               hjust = 0.05, vjust = -.7)+
    th

  }

#grid.arrange(
  Plotting(VOgeo)+coord_fixed()#,
             Plotting(VOgeo1, 
                      AntallNye = 1)+coord_fixed()#,
             Plotting(VOgeo2, 
                      AntallNye = 1)+coord_fixed()#,
             Plotting(VOgeo3, 
                      AntallNye = 2)+coord_fixed()#, ncol = 4, nrow = 1)
```

  
