---
title: "De små tingene"
description: > 
  Hvis jeg gjør det jeg kan på mitt kontor, og du på ditt så må vi vel alle bli fornøyde med samfunnet?
draft: true
author:
  - name: Endre Grüner Ofstad
bibliography: bibliography.bib
categories:
  - Forvaltning
  - Økosystem
output:
  distill::distill_article:
    self_contained: false
---

Google tipset meg nylig om en artikkel jeg kunne ha interesse av. En kronikk på [forskersonen](https://forskersonen.no/kronikk-meninger-politikk/bevaring-av-okosystemene-fullt-og-helt-eller-stykkevis-og-delt/1750403) skrevet av en rekke forskere med Aas i spissen. Kronikken ble skrevet på bakgrunn av artikkelen [Ecosystem-based management: Miracle or Mirage? Mapping and rapid evidence assessment of international and Nordic research literature on ecosystem-based management](https://brage.nina.no/nina-xmlui/handle/11250/2648103). 

Artikkelen tar for seg økosystembasert forvaltning og implementering av denne. Økosystembasert forvaltning er et begrep uten en markant definisjon, men som omhandler en helhetlig tilnærming til forvaltningen av økosystem. At flere sektorer involveres og at forvaltningen hever blikket fra enkeltarter til økosystem. Videre skal forvaltningen skje på en bærekraftig måte og sikre at økosystemet har en god økologisk status [^1] . Dette er et begrep som er blitt stadig mer populært de siste årene. Artikkelen påpeker mange utfordrende faktorer for tilnærmingen hvor den største trolig er sektororganiseringen.

[^1]: Jfr. [Vanndirektivet](https://lovdata.no/forskrift/2006-12-15-1446/§4) som krever at vannforekomster skal ha en god økologisk tilstand.

Sektoransvarsprinsippet reflektere enkelt sagt at jeg ikke skal fortelle deg hvordan du best skal gjøre jobben din, og *vice versa*. Kommuner bestemmer innenfor kommunen sin, Statens Vegvesen bestemmer hvor og hvordan veier bygges og så videre. Så lenge loven ikke sier noe annet. [Naturmangfoldloven](https://lovdata.no/lov/2009-06-19-100/§10) forplikter at alle offentlige beslutninger som berører naturmangfold skal ta en økosystemtilnærming på hvordan beslutningen vil påvirke den totale belastningen på økosystemet. En vellykket implementering av dette innebærer altså at alle parter er klar over hverandres handlinger i dag og i fremtiden, og er enige om hva disse handlingene innebærer for økosystemet. Ikke småtteri altså [^2].

[^2]: Og hvor slutter og starter økosystemet?


## De små tingene
@Kahn1966 introduserte konseptet 'de små avgjørelsers tyranni' ("The Tyranny of Small Decisions"). Eventuelt 'enkeltvedtakets tyranni'? ['Bit-for-bit-tyranni'](https://evalueringsportalen.no/evaluering/spredt-utbygging-og-jordvern-om-omfang-og-drivkrefter-bak-bygging-paa-jordbruksarealer/Spredt_utbygging_og_jordvern.pdf/@@inline)? Hvor du og jeg hver for oss foretar små avgjørelser til vårt eget beste. Du tar flyet til Oslo (det er raskest), og jeg tar bilen (så jeg kan kjøpe boller på Espa). Det er det som rasjonelt gir mening for hver av oss i vår situasjon. Og sånn går dagene, og vipps så blir togbanen lagt ned siden de ikke tjener nok. Ingen av oss ønsket det. Vi begge vil ha toget der som en mulighet - for når bestemor skal komme på besøk, eller fruen trenger bilen en helg og jeg ikke vil ta flyet. Likeså, for alle andre avgjørelser i det ganske land. Vi fatter alle avgjørelser ut fra hva vi anser som rasjonelt ut fra vårt ståsted. Ut fra hva vårt kunnskapsgrunnlag, ansvarsområde og interesser. 

På politisk nivå kan dette skyldes insentiver for godvilje ved neste valg. Eller at den enkelte saksbehandler rasjonaliserer seg dithen at bare *en* til kan vel ikke spille noen rolle? Og sakte, men sikkert [forsvinner strandsonen vår](https://www.dagsavisen.no/nyheter/innenriks/tusenvis-av-byggetillatelser-i-strandsonen-er-blitt-gitt-pa-feil-grunnlag-1.1119069) til tross for at det er et byggeforbud der. Noe som fjerner tilgangen til et fellesgode - havet - for folk flest. 


## En kopp kaffe
Avgjørelser fattes innenfor hvert vårt ansvarsområde. Vår sektor. Men økosystemets grenser følger ikke kommunens geografiske grenser, ei heller bryr den seg om avgjørelsen fattes av grunneier, kommune eller stat. Elven renner gjennom flere kommuner, og avgjørelsene gjort i en kommune vil derfor ha en innvirkning hos nabokommunen. Aas og kolleger påpeker hvordan den enkelte sektor, foretar avgjørelser som gagner egne interesser fremfor helheten [^3]. Dette til tross av å være styrt av felles lover som skal sikre en økosystembasert forvaltning. 

[^3]: Dette har mange fellestrekk med konseptet ['allmenningens tragedie'](https://www.hendrix.edu/uploadedFiles/Admission/GarrettHardinArticle.pdf). Noe som fortjener et eget blogginnlegg.



Odum [@Odum1982] foreslo at regionale strukturer (slik som Fylkesmann, Fylkeskommune) ville kunne sikre en samkjøring av lokale avgjørelser. Videre vil regelverk som Plan- og Bygningsloven sikre engasjement. Plan- og Bygningsloven er med å på sikre prosesser hvor alle interesserte parter skal bli hør, og [planer som kan strekke seg lengre enn politiske perioder](https://www.stortinget.no/no/Saker-og-publikasjoner/Sporsmal/Skriftlige-sporsmal-og-svar/Skriftlig-sporsmal/?qid=80887&fbclid=IwAR1pV4rTXtBKNVP9A9Co-JoJcAWF6Kvs-7wwj3LPF2dHHHgGsYhfK-HBFD4). 


Til sist, og aller viktigst løses det ved god kommunikasjon. Fra grunneier til kommune til stat til grunneier...Mye informasjon og kunnskap forsvinner når vi sitter i hver vår sektor og på hver vår tue. Mye kan kanskje løses ved å invitere hverandre på møter, og legge hverandre til som kopimottakere, men jeg tror også at veldig mye informasjon kan utveksles ved å ta seg kaffekopp og slå av en fem-minutters prat. 

